name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    # Checkout this repository
    - name: Checkout this repository
      uses: actions/checkout@v2
    
    # DocFx metadata
    - uses: nikeee/docfx-action@master
      name: DocFx metadata
      with:
        args: metadata

    # DocFx build
    - uses: nikeee/docfx-action@master
      name: DocFx build
      with:
        args: build

    # Publish to Github Pages
    - uses: maxheld83/ghpages@v0.3.0
      env:
        BUILD_DIR: _site/
        GH_PAT: ${{ secrets.GH_PAT }}