name: Build

on: [push, repository_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    # Checkout this repository
    - name: Checkout this repository
      uses: actions/checkout@v2

    # Checkout Unity plugin master branch
    - uses: actions/checkout@v2
      name: Checkout Unity plugin master branch
      with:
        repository: OndrejNepozitek/ProceduralLevelGenerator-Unity
        ref: master
        path: src/master

    # Checkout Unity plugin dev branch
    - uses: actions/checkout@v2
      name: Checkout Unity plugin dev branch
      with:
        repository: OndrejNepozitek/ProceduralLevelGenerator-Unity
        ref: dev
        path: src/dev
    
    # DocFx metadata
    - uses: nikeee/docfx-action@master
      name: DocFx metadata
      with:
        args: metadata

    # Install node
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # Install js-yaml
    - name: Install js-yaml
      run: npm install js-yaml

    # Run toc.js
    - name: Run toc.js
      run: sudo node toc.js

    # DocFx build
    - uses: nikeee/docfx-action@master
      name: DocFx build
      with:
        args: build

    # Publish to Github Pages
    - uses: maxheld83/ghpages@v0.3.0
      env:
        BUILD_DIR: _site/
        GH_PAT: ${{ secrets.GH_PAT }}